TEST_CASES = [
    (0, 0, [' (accept)']),
    (0, 1, ['a (accept)', 'b (rejected)']),
    (0, 2, ['aa (rejected)', 'ab (rejected)', 'ba (rejected)', 'bb (accept)']),
    (0, 3, ['aaa (accept)', 'aba (accept)', 'baa (rejected)', 'bab (accept)', 'bba (rejected)', 'bbb (accept)']),
    (0, 4, ['baaa (rejected)', 'baab (accept)', 'baba (rejected)', 'babb (accept)', 'bbba (rejected)', 'bbbb (accept)']),
    (1, 0, [' (accept)']),
    (1, 1, ['a (rejected)', 'b (rejected)']),
    (1, 2, ['aa (accept)', 'ba (accept)']),
    (1, 3, None),
    (1, 4, None),
    (2, 0, [' (rejected)']),
    (2, 1, ['a (accept)']),
    (2, 2, None),
    (2, 3, None),
    (2, 4, None),
    (3, 0, [' (accept)']),
    (3, 1, None),
    (3, 2, None),
    (3, 3, None),
    (3, 4, None),
    (4, 0, [' (rejected)']),
    (4, 1, ['a (rejected)', 'b (accept)']),
    (4, 2, ['aa (rejected)', 'ab (accept)', 'ba (rejected)', 'bb (accept)']),
    (4, 3, ['aaa (rejected)', 'aab (accept)', 'aba (rejected)', 'abb (accept)', 'bba (rejected)', 'bbb (accept)']),
    (4, 4, ['aaaa (rejected)', 'aaab (accept)', 'aaba (rejected)', 'aabb (accept)', 'abba (rejected)', 'abbb (accept)', 'bbba (rejected)', 'bbbb (accept)']),
    (5, 0, [' (accept)']),
    (5, 1, ['a (rejected)', 'b (accept)']),
    (5, 2, ['ba (rejected)', 'bb (accept)']),
    (5, 3, ['bba (rejected)', 'bbb (accept)']),
    (5, 4, ['bbba (rejected)', 'bbbb (accept)']),
    (6, 0, [' (rejected)']),
    (6, 1, None),
    (6, 2, None),
    (6, 3, None),
    (6, 4, None),
]