TEST_CASES = [(0, 0, [' (rejected)']),
 (0, 1, ['a (accept)', 'b (rejected)', 'c (rejected)']),
 (0, 2, ['aa (rejected)', 'ba (accept)', 'bb (rejected)', 'bc (rejected)', 'ca (accept)']),
 (0,
  3,
  ['aaa (accept)',
   'aab (rejected)',
   'aac (rejected)',
   'baa (rejected)',
   'bba (accept)',
   'bbb (rejected)',
   'bbc (rejected)',
   'bca (accept)',
   'caa (rejected)',
   'cab (rejected)',
   'cac (rejected)']),
 (0,
  4,
  ['aaaa (rejected)',
   'aaba (accept)',
   'aabb (rejected)',
   'aabc (rejected)',
   'aaca (accept)',
   'baaa (accept)',
   'baab (rejected)',
   'baac (rejected)',
   'bbaa (rejected)',
   'bbba (accept)',
   'bbbb (rejected)',
   'bbbc (rejected)',
   'bbca (accept)',
   'bcaa (rejected)',
   'bcab (rejected)',
   'bcac (rejected)',
   'caaa (accept)',
   'caab (rejected)',
   'caac (rejected)',
   'caba (accept)',
   'cabb (rejected)',
   'cabc (rejected)',
   'caca (accept)',
   'cacb (rejected)',
   'cacc (rejected)']),
 (1, 0, [' (accept)']),
 (1, 1, ['a (rejected)']),
 (1, 2, ['aa (accept)', 'ab (rejected)', 'ac (rejected)']),
 (1, 3, ['aaa (rejected)', 'aba (accept)', 'abb (rejected)', 'abc (rejected)', 'aca (accept)']),
 (1,
  4,
  ['aaaa (accept)',
   'aaab (rejected)',
   'aaac (rejected)',
   'abaa (rejected)',
   'abba (accept)',
   'abbb (rejected)',
   'abbc (rejected)',
   'abca (accept)',
   'acaa (rejected)',
   'acab (rejected)',
   'acac (rejected)']),
 (2, 0, [' (rejected)']),
 (2, 1, ['a (accept)', 'b (rejected)', 'c (rejected)']),
 (2, 2, ['aa (rejected)', 'ba (accept)', 'bb (rejected)', 'bc (rejected)', 'ca (accept)']),
 (2,
  3,
  ['aaa (accept)',
   'aab (rejected)',
   'aac (rejected)',
   'baa (rejected)',
   'bba (accept)',
   'bbb (rejected)',
   'bbc (rejected)',
   'bca (accept)',
   'caa (rejected)',
   'cab (rejected)',
   'cac (rejected)']),
 (2,
  4,
  ['aaaa (rejected)',
   'aaba (accept)',
   'aabb (rejected)',
   'aabc (rejected)',
   'aaca (accept)',
   'baaa (accept)',
   'baab (rejected)',
   'baac (rejected)',
   'bbaa (rejected)',
   'bbba (accept)',
   'bbbb (rejected)',
   'bbbc (rejected)',
   'bbca (accept)',
   'bcaa (rejected)',
   'bcab (rejected)',
   'bcac (rejected)',
   'caaa (accept)',
   'caab (rejected)',
   'caac (rejected)',
   'caba (accept)',
   'cabb (rejected)',
   'cabc (rejected)',
   'caca (accept)',
   'cacb (rejected)',
   'cacc (rejected)']),
 (3, 0, [' (accept)']),
 (3, 1, ['a (rejected)']),
 (3, 2, ['aa (accept)', 'ab (rejected)', 'ac (rejected)']),
 (3, 3, ['aaa (rejected)', 'aba (accept)', 'abb (rejected)', 'abc (rejected)', 'aca (accept)']),
 (3,
  4,
  ['aaaa (accept)',
   'aaab (rejected)',
   'aaac (rejected)',
   'abaa (rejected)',
   'abba (accept)',
   'abbb (rejected)',
   'abbc (rejected)',
   'abca (accept)',
   'acaa (rejected)',
   'acab (rejected)',
   'acac (rejected)']),
 (4, 0, [' (rejected)']),
 (4, 1, ['a (accept)']),
 (4, 2, ['aa (rejected)', 'ab (rejected)', 'ac (rejected)']),
 (4,
  3,
  ['aaa (accept)',
   'aab (rejected)',
   'aac (rejected)',
   'aba (accept)',
   'abb (rejected)',
   'abc (rejected)',
   'aca (accept)',
   'acb (rejected)',
   'acc (rejected)']),
 (4,
  4,
  ['aaaa (rejected)',
   'aaba (accept)',
   'aabb (rejected)',
   'aabc (rejected)',
   'aaca (accept)',
   'abaa (rejected)',
   'abba (accept)',
   'abbb (rejected)',
   'abbc (rejected)',
   'abca (accept)',
   'acaa (rejected)',
   'acba (accept)',
   'acbb (rejected)',
   'acbc (rejected)',
   'acca (accept)']),
 (5, 0, [' (accept)']),
 (5, 1, ['a (rejected)', 'b (rejected)', 'c (rejected)']),
 (5,
  2,
  ['aa (accept)',
   'ab (rejected)',
   'ac (rejected)',
   'ba (accept)',
   'bb (rejected)',
   'bc (rejected)',
   'ca (accept)',
   'cb (rejected)',
   'cc (rejected)']),
 (5,
  3,
  ['aaa (rejected)',
   'aba (accept)',
   'abb (rejected)',
   'abc (rejected)',
   'aca (accept)',
   'baa (rejected)',
   'bba (accept)',
   'bbb (rejected)',
   'bbc (rejected)',
   'bca (accept)',
   'caa (rejected)',
   'cba (accept)',
   'cbb (rejected)',
   'cbc (rejected)',
   'cca (accept)']),
 (5,
  4,
  ['aaaa (accept)',
   'aaab (rejected)',
   'aaac (rejected)',
   'abaa (rejected)',
   'abba (accept)',
   'abbb (rejected)',
   'abbc (rejected)',
   'abca (accept)',
   'acaa (rejected)',
   'acab (rejected)',
   'acac (rejected)',
   'baaa (accept)',
   'baab (rejected)',
   'baac (rejected)',
   'bbaa (rejected)',
   'bbba (accept)',
   'bbbb (rejected)',
   'bbbc (rejected)',
   'bbca (accept)',
   'bcaa (rejected)',
   'bcab (rejected)',
   'bcac (rejected)',
   'caaa (accept)',
   'caab (rejected)',
   'caac (rejected)',
   'cbaa (rejected)',
   'cbba (accept)',
   'cbbb (rejected)',
   'cbbc (rejected)',
   'cbca (accept)',
   'ccaa (rejected)',
   'ccab (rejected)',
   'ccac (rejected)'])]